### ISSUE TITLE
Score value in the `repos.json`

### ISSUE THREAD

**Issue by 3cpt** [SAP/project-portal-for-innersource#29]
Hi. How do you calculate the score? I was trying to test the [repository-activity-score](https://patterns.innersourcecommons.org/p/repository-activity-score) pattern algorithm against the `repos.json` but I don't get the same values?

Is the data mocked, including the `score`?

Thanks

**Comment by spier** [comment]
I know that the rest of the data in [repos.json](https://github.com/SAP/project-portal-for-innersource/blob/main/repos.json) is definitely mocked - especially as SAP is likely not in the business of maintaining planets :))

So I would assume that the scores in that file are mocked too.

In the [crawler implementation](https://github.com/spier/innersource-crawler-ruby/blob/main/crawler.rb#L9-L11) that I started (in a separate repo) I am not calculating the mentioned repository-activity-score yet either, but rather something super simplistic as a placeholder. However you were game to help adding the real activity-score calculation to that, that would be awesome 😄

**Comment by 3cpt** [comment]
> I know that the rest of the data in [repos.json](https://github.com/SAP/project-portal-for-innersource/blob/main/repos.json) is definitely mocked - especially as SAP is likely not in the business of maintaining planets :))

We never know, the sky isn't the limit anymore! 😄 

> In the [crawler implementation](https://github.com/spier/innersource-crawler-ruby/blob/main/crawler.rb#L9-L11) that I started (in a separate repo) I am not calculating the mentioned repository-activity-score yet either, but rather something super simplistic as a placeholder. However you were game to help adding the real activity-score calculation to that, that would be awesome 😄

I saw that implementation and the comment too. My question is because I'm studying the algorithm trying to match with some real cases. I need to be sure that I found some parts in the pattern example that need to be fixed - need to open an Issue in the InnerSourceCommons patterns repo. 😅 

And if I had time I will try to implement the algorithm in Ruby - nice opportunity to learn - as I'm doing to the [innersource-crawler](https://github.com/zkoppert/innersource-crawler/issues/17)

Thanks

**Comment by spier** [comment]
Hehe nice, you already found all the right places.

Looking forward to see you on the InnerSourcePatterns repo then, as I am involved with that too :)
