### ISSUE TITLE
List-Card view changes after closing details view 

### ISSUE THREAD

**Issue by thomaswoyke** [SAP/project-portal-for-innersource#31]
How to reproduce 
* open https://sap.github.io/project-portal-for-innersource/#display=card
* Switch to list view 
* click on any project -> detail view opens
* close detail view 
* Observed behavior: projects are shown in card view 
* Expected behavior: List view mode is kept

**Comment by Michadelic** [comment]
Dear @thomaswoyke, thank you very much for reporting this bug. I analyized it and provided a fix.
The dialog's close button had the href="#!" that accidentially removed all URL parameters.

Enjoy :-)
