### ISSUE TITLE
Customize the portal

### ISSUE THREAD

**Issue by ranandverint** [SAP/project-portal-for-innersource#35]
Is there a way to use custom images as project logos?
Currently the portal uses the avatar_URL to add logos for each projects.
What if we had 1 org dedicated for innersource, then all the project logos will be the same.
Any ideas?

**Comment by spier** [comment]
I don't understand what you meant here:
> What if we had 1 org dedicated for innersource, then all the project logos will be the same.

Why would that be the case?

However I believe if your repo has an `innersource.json` file that your crawler picks up, then you can set a custom logo for the project in there. See [these docs](https://github.com/SAP/project-portal-for-innersource/blob/main/docs/LISTING.md#syntax-definition-of-innersourcejson).

**Comment by ranandverint** [comment]
In my company, we are using GHES & we have multi-org setup divided among different BUs. But for the innersource culture we have 1 dedicated Organization in our Github, where everyone is added & all the projects that want to be innersourced, need to be present inside this Org. Hope this makes the ask clear 😃 
> I don't understand what you meant here:
> 
> > What if we had 1 org dedicated for innersource, then all the project logos will be the same.


Thanks for the quick response 👍🏻 
The addition of `innersource.json` did help . I missed it somehow while going through the documentation.

**Comment by spier** [comment]
Ah, I think I understand what you mean now.

I took a look at [the logic](https://github.com/SAP/project-portal-for-innersource/blob/main/scripts/index.js#L358-L362) that picks the logo to display, and while I don't find it easy to read/understand, it does look like the fallback option when no logo is provided is to use the avatar of the org that owns the repo, just like you were saying (i.e. `oRepo.owner.avatar_url`).

But good to hear that the link to the docs helped :)

Feel free to close this issue if that has solved your problem.

**Comment by ranandverint** [comment]
I wouldn't say, that my issue is completely resolved, but I did get a starting point to look at.
So happy to close this issue 😃

**Comment by spier** [comment]
👍 feel free to restart the conversation if you run in to further issues.
I guess opening a new issue will be the way to go then, or re-opening this one, if that is an option in GitHub?
Cheers

**Comment by ranandverint** [comment]
Thanks for your help @spier .. I was able to get the job done 👍🏻 
Really appreciate your quick response 😃

**Comment by spier** [comment]
Very nice to hear that @ranandverint !

Btw once your org has made some experiences with the portal, and you want to share that, then you can always add your org as a "Known Instance" to this pattern here. That helps others to understand how this pattern (and the portal) can be used. https://patterns.innersourcecommons.org/p/innersource-portal

_Full disclosure:_ I am one of the maintainers of those patterns :)
