### ISSUE TITLE
Adding Authentication to the Portal

### ISSUE THREAD

**Issue by Wayne-Ennis** [SAP/project-portal-for-innersource#44]
Hey i have the need to have our portal Secured behind an OAUTH2 IDP.  Has anyone explored options for this?  is it possible for me to just install my library, then add the methods?  What are your recommendations?
Thanks

**Comment by spier** [comment]
hey @Wayne-Ennis , on a tangent, if you like you can get your org added to the [ADOPTERS](https://github.com/SAP/project-portal-for-innersource/blob/main/ADOPTERS.md) page.

Always great to learn about other orgs using this project in the wild. And if you want to add a short description of your auth approach, wouldn't hurt either.

Cheers :)
