### ISSUE TITLE
Display of projects without Activity Score

### ISSUE THREAD

**Issue by spier** [SAP/project-portal-for-innersource#6]
According to [the docs](https://github.com/SAP/project-portal-for-innersource/blame/main/README.md#L77) the calculation of an Activity Score is optional. 

However when creating a `repos.json` without `_InnerSourceMetadata.score` then the UI shows `false` instead of the score. (see screenshot)

I am wondering if that is the expected behavior?

![project-without-score](https://user-images.githubusercontent.com/163029/103354810-d8610780-4aac-11eb-8cd2-f2699c274617.JPG)

**Comment by spier** [comment]
I further notices that in the project popup a missing `score` leads to a display of `undefined`. See screenshot.

![project-without-score-popup](https://user-images.githubusercontent.com/163029/103355179-ecf1cf80-4aad-11eb-9823-85816d983f02.JPG)

**Comment by Michadelic** [comment]
fixed with #9
